"""...class licences

Revision ID: 1907fafce265
Revises: e2fc2015019f
Create Date: 2023-08-20 05:11:01.428177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1907fafce265'
down_revision = 'e2fc2015019f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('licences')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('date_debut', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('date_fin', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='licences_pkey')
    )
    # ### end Alembic commands ###
