"""Ajout de la relation entre services et users

Revision ID: 5ae5295b4304
Revises: 9770b4f6f14f
Create Date: 2023-08-06 23:04:09.971120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae5295b4304'
down_revision = '9770b4f6f14f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('services_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'services', ['services_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('services_id')

    # ### end Alembic commands ###
