"""...

Revision ID: 8dff4daa76e5
Revises: e0f3fa004887
Create Date: 2023-08-24 09:47:30.713817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dff4daa76e5'
down_revision = 'e0f3fa004887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peripheriques', schema=None) as batch_op:
        batch_op.drop_constraint('peripheriques_model_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peripheriques', schema=None) as batch_op:
        batch_op.create_unique_constraint('peripheriques_model_key', ['model'])

    # ### end Alembic commands ###
