"""IP en string

Revision ID: c25cd8d68042
Revises: 7d8e43ae8df8
Create Date: 2023-08-18 00:44:07.448417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c25cd8d68042'
down_revision = '7d8e43ae8df8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imprimantes', schema=None) as batch_op:
        batch_op.alter_column('adresse_ip',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=128),
               existing_nullable=False)

    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.alter_column('adresse_ip',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=128),
               existing_nullable=False)

    with op.batch_alter_table('serveurs', schema=None) as batch_op:
        batch_op.alter_column('adresse_ip',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('serveurs', schema=None) as batch_op:
        batch_op.alter_column('adresse_ip',
               existing_type=sa.String(length=128),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.alter_column('adresse_ip',
               existing_type=sa.String(length=128),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('imprimantes', schema=None) as batch_op:
        batch_op.alter_column('adresse_ip',
               existing_type=sa.String(length=128),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
