"""système => systeme

Revision ID: e2fc2015019f
Revises: c25cd8d68042
Create Date: 2023-08-18 00:50:18.355922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2fc2015019f'
down_revision = 'c25cd8d68042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('systeme', sa.String(length=128), nullable=False))
        batch_op.drop_column('système')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('système', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
        batch_op.drop_column('systeme')

    # ### end Alembic commands ###
