"""rectification des erreurs & migrations des cles primaires

Revision ID: fa86acdb9c0a
Revises: defed309623f
Create Date: 2023-08-17 01:29:14.392430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa86acdb9c0a'
down_revision = 'defed309623f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commutateurs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marque_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'types', ['type_id'], ['id'])
        batch_op.create_foreign_key(None, 'marques', ['marque_id'], ['id'])

    with op.batch_alter_table('imprimantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marque_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'types', ['type_id'], ['id'])
        batch_op.create_foreign_key(None, 'marques', ['marque_id'], ['id'])

    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marque_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'types', ['type_id'], ['id'])
        batch_op.create_foreign_key(None, 'marques', ['marque_id'], ['id'])

    with op.batch_alter_table('serveurs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marque_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'marques', ['marque_id'], ['id'])
        batch_op.create_foreign_key(None, 'types', ['type_id'], ['id'])

    with op.batch_alter_table('telephones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marque_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'types', ['type_id'], ['id'])
        batch_op.create_foreign_key(None, 'marques', ['marque_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telephones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('type_id')
        batch_op.drop_column('marque_id')

    with op.batch_alter_table('serveurs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('type_id')
        batch_op.drop_column('marque_id')

    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('type_id')
        batch_op.drop_column('marque_id')

    with op.batch_alter_table('imprimantes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('type_id')
        batch_op.drop_column('marque_id')

    with op.batch_alter_table('commutateurs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('type_id')
        batch_op.drop_column('marque_id')

    # ### end Alembic commands ###
